### PR TITLE
Implement AccessTokenService compatible with lcobucci/jwt v5

### PR DESCRIPTION
**Pull request by StefanLuijtenWolfpack**

### CODE REVIEW

**Comment by dimitar-petro-v** [comment]
I'm unsure if this change works with older versions of PHP? If we merge this to main and make a release, we probably should double-check other projects that use this package and make sure they are not set to latest.

**Comment by robjanssen** [comment]
So this is basically the same trick I've done with the SRP because of those changes in the original library.

@dimitar-petro-v this should only be an issue if you use the package as latest or main, instead of having it pinned to a version. This is effectively a major release (you need to have a passphrase set).

Additionally, since this is an open source project, there's no good way to tell ;)

**Comment by dimitar-petro-v** [comment]
FTR one has this package set to `dev-master` and the other is set to "^2.0.1"

**Comment by StefanLuijtenWolfpack** [comment]
Like said above, that is the mistake of the other projects and not relevant to this package.
Since v2.0 of this package  PHP version `^8.1` required and started using `^5.2` from `lcobucci/jwt`.
However before this PR the code was not functioning since it used code from `3.x` that was not longer in the new version.

**Review by dimitar-petro-v — APPROVED** [review]

**Review by robjanssen — APPROVED** [review]

**Pull request merged**
